spring.application.name=lms-backend

jwt.secret=mySecretKeyForJWTTokenGenerationWhichIsVeryLong123456789
jwt.expiration=86400000

loan.activation.delay.minutes=1


logging.level.com.lms=DEBUG

# Stripe (test mode)
payment.stripe.secret-key=${STRIPE_SECRET_KEY}
payment.stripe.publishable-key=${STRIPE_PUBLISHABLE_KEY}
payment.stripe.webhook-secret=
