spring.application.name=lms-backend

jwt.secret=mySecretKeyForJWTTokenGenerationWhichIsVeryLong123456789
jwt.expiration=86400000

logging.level.com.lms=DEBUG
logging.level.org.springframework.web.servlet.mvc.method.annotation=DEBUG
